apiVersion: v1
kind: Pod
metadata:
  name: webapp
spec:
  volumes:
  - name: webapp
    hostPath: 
      path: /var/log/webapp
  containers:
  - env:
    - name: LOG_HANDLERS
      value: file
    image: kodekloud/event-simulator
    imagePullPolicy: Always
    name: event-simulator
    volumeMounts:
      - name: webapp
        mountPath: /log
